import { PositionsInterface } from './Positions';
import { HiStateInterface } from './HiState';
import { ExperienceStylePropsInterface } from './ExperienceStyleProps';
import { ProfileInterface } from './info/Profile';
import { AboutInterface } from './info/About';
import { CardDialogImageInterface, CardDialogInfoInterface, CardDialogContentInterface, CardDataInterface, TimelineInterface } from './info/Timeline';
import { BlogInterface } from './info/Blog';
import { AbilityInterface, AbilityBlockInterface, SubsectionsInterface, AbilitiesInterface } from './info/Abilities';
import { PlaceInterface, PictureInterface, TravelInterface } from './info/Travel';
import { InfoInterface } from './info/Info';

export type Positions = PositionsInterface;
export type HiState = HiStateInterface;
export type ExperienceStyleProps = ExperienceStylePropsInterface;

export type Profile = ProfileInterface;
export type About = AboutInterface;
export type CardDialogImage = CardDialogImageInterface;
export type CardDialogInfo = CardDialogInfoInterface;
export type CardDialogContent = CardDialogContentInterface;
export type CardData = CardDataInterface;
export type Timeline = TimelineInterface;
export type Blog = BlogInterface;
export type Ability = AbilityInterface;
export type AbilityBlock = AbilityBlockInterface;
export type Subsection = SubsectionsInterface;
export type Abilities = AbilitiesInterface;
export type Place = PlaceInterface;
export type Picture = PictureInterface;
export type Travel = TravelInterface;
export type Info = InfoInterface;